sonar.projectKey=hendro17_Hitung-SWDKLLJ_69cbe75d-b3cb-45a3-9c05-aa75565d6df8
sonar.sources=src
sonar.exclusions=**/*.d.ts,**/assets/**,src/views/**,src/services/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts,src/router/**,src/assets/**,src/App.vue,src/views/**,src/services/**,src/components/AppBreadcrumb.vue,src/components/AppSidebar.vue,src/composables/useKeringanan.ts,src/composables/usePwaInstall.ts,src/stores/superAdminStore.ts,src/domain/types.ts
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/views/**,src/services/**,src/domain/csv-parser.ts
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8,e9,e10
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=src/domain/csv-parser.ts
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=src/domain/hitung.ts
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=src/domain/**
sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S1481
sonar.issue.ignore.multicriteria.e4.resourceKey=src/**
sonar.issue.ignore.multicriteria.e5.ruleKey=typescript:S106
sonar.issue.ignore.multicriteria.e5.resourceKey=src/composables/useTarif.ts,src/services/firebase.ts
sonar.issue.ignore.multicriteria.e6.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e6.resourceKey=src/domain/csv-parser.ts
sonar.issue.ignore.multicriteria.e7.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e7.resourceKey=src/domain/hitung.ts
sonar.issue.ignore.multicriteria.e8.ruleKey=javascript:S1192
sonar.issue.ignore.multicriteria.e8.resourceKey=src/domain/**
sonar.issue.ignore.multicriteria.e9.ruleKey=javascript:S1481
sonar.issue.ignore.multicriteria.e9.resourceKey=src/**
sonar.issue.ignore.multicriteria.e10.ruleKey=javascript:S106
sonar.issue.ignore.multicriteria.e10.resourceKey=src/composables/useTarif.ts,src/services/firebase.ts
