sonar.projectKey=hendro17_Hitung-SWDKLLJ_69cbe75d-b3cb-45a3-9c05-aa75565d6df8
sonar.sources=src
sonar.exclusions=**/*.d.ts,**/assets/**,src/views/**,src/services/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts,src/router/**,src/assets/**,src/App.vue,src/views/**,src/services/**,src/components/AppBreadcrumb.vue,src/components/AppSidebar.vue,src/composables/useKeringanan.ts,src/composables/usePwaInstall.ts,src/stores/superAdminStore.ts,src/domain/types.ts
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/views/**,src/services/**,src/domain/csv-parser.ts
